### Section A: Concept Application

In [148]:
import numpy as np
import pandas as pd

In [149]:
df = pd.read_csv(r"C:\Users\patel prit\OneDrive\Desktop\Assessment\ML\Assessment\UnSupervised\WA_Fn-UseC_-HR-Employee-Attrition.csv")

In [150]:
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

* 1. You identify 'Attrition' as the target variable in the IBM HR dataset. What is the
difference between a feature and a label in a supervised learning problem?

#### Ans:
Feature:
The input variables used by the model to make predictions are called features.
Examples: Age, MonthlyIncome, JobRole, Education.

Label:
The output or target variable that the model tries to predict is called the label.
In the IBM HR dataset, 'Attrition' is the label because it indicates whether an employee leaves the company (Yes/No).

* 2. The HR attrition problem predicts a Yes or No outcome. What type of ML
problem is this — regression or classification?

#### Ans:

The HR attrition problem is a **Classification** problem because the target variable
'Attrition' has two categories: Yes and No.

The model predicts a class label rather than a continuous numerical value.

* 3. Your model performs well on training data but poorly on unseen test data.
What is this condition called, and what causes it?

#### Ans:
##### This condition is called Overfitting.

Overfitting occurs when a model learns the training data too closely,
including noise and unnecessary patterns. As a result, it achieves high
accuracy on training data but performs poorly on unseen test data.

* 4. The ML workflow follows a fixed sequence of stages. List the stages of the ML
workflow in order.

#### Ans:
Here is the quick, high-level summary of the standard ML workflow:

1. **Data Collection:** Gather the necessary raw data.
2. **Data Preparation:** Clean the data and handle missing values.
3. **Feature Engineering:** Select and transform variables for the model.
4. **Model Training:** Feed data into algorithms to learn patterns.
5. **Model Evaluation:** Test and fine-tune the model's performance.
6. **Model Deployment:** Launch the model into a live production environment.
7. **Monitoring & Maintenance:** Track real-world performance and retrain when necessary.

* 5. You keep a separate test set that the model never sees during training. What is the purpose of this test set?

#### Ans:
The main purpose of a test set is used to evaluate how well a trained machine learning model performs on **new, unseen data**.

It does two crucial things:

* **Checks Generalization:** It proves whether the model actually learned the underlying patterns or just memorized the training data (**overfitting**).
* **Gives an Unbiased Score:** It acts as a final, honest grade of the model's accuracy before you deploy it.

### Section B: Practical Task

* 1. Create a comprehensive Data Dictionary mapping all 35 IBM HR features to their respective statistical data types.

| # | Feature Name | Statistical Data Type | Pandas Type | Description & Scale |
| :--- | :--- | :--- | :--- | :--- |
| 1 | **Age** | Quantitative (Discrete/Ratio) | `int64` | Employee age in years (18–60). |
| 2 | **Attrition** | Qualitative (Nominal/Binary) | `object` | **Target Variable**: Employee turnover status (`Yes`/`No`). |
| 3 | **BusinessTravel** | Qualitative (Ordinal) | `object` | Frequency of travel (`Non-Travel` < `Travel_Rarely` < `Travel_Frequently`). |
| 4 | **DailyRate** | Quantitative (Continuous/Ratio) | `int64` | Daily billing/cost rate of the employee. |
| 5 | **Department** | Qualitative (Nominal) | `object` | Department of employment (`Sales`, `Research & Development`, `Human Resources`). |
| 6 | **DistanceFromHome** | Quantitative (Continuous/Ratio) | `int64` | Distance from home to work in miles/kilometers. |
| 7 | **Education** | Qualitative (Ordinal) | `int64` | Level of education (1: Below College, 2: College, 3: Bachelor, 4: Master, 5: Doctor). |
| 8 | **EducationField** | Qualitative (Nominal) | `object` | Field of study (`Life Sciences`, `Medical`, `Marketing`, `Technical Degree`, `Human Resources`, `Other`). |
| 9 | **EmployeeCount** | Quantitative (Discrete) | `int64` | **Constant Feature**: Always `1`. Usually dropped during preprocessing. |
| 10 | **EmployeeNumber** | Qualitative (Nominal) | `int64` | **Unique Identifier**: Employee ID. Dropped during modeling. |
| 11 | **EnvironmentSatisfaction** | Qualitative (Ordinal) | `int64` | Workplace environment satisfaction (1: Low, 2: Medium, 3: High, 4: Very High). |
| 12 | **Gender** | Qualitative (Nominal/Binary) | `object` | Gender of the employee (`Male`, `Female`). |
| 13 | **HourlyRate** | Quantitative (Continuous/Ratio) | `int64` | Hourly wage rate. |
| 14 | **JobInvolvement** | Qualitative (Ordinal) | `int64` | Level of job involvement (1: Low, 2: Medium, 3: High, 4: Very High). |
| 15 | **JobLevel** | Qualitative (Ordinal) | `int64` | Professional tier hierarchy within the company (1 to 5). |
| 16 | **JobRole** | Qualitative (Nominal) | `object` | Specific job role (`Sales Executive`, `Research Scientist`, `Laboratory Technician`, etc.). |
| 17 | **JobSatisfaction** | Qualitative (Ordinal) | `int64` | Job satisfaction rating (1: Low, 2: Medium, 3: High, 4: Very High). |
| 18 | **MaritalStatus** | Qualitative (Nominal) | `object` | Marital status (`Single`, `Married`, `Divorced`). |
| 19 | **MonthlyIncome** | Quantitative (Continuous/Ratio) | `int64` | Monthly salary in local currency units. |
| 20 | **MonthlyRate** | Quantitative (Continuous/Ratio) | `int64` | Monthly utility/billing rate. |
| 21 | **NumCompaniesWorked** | Quantitative (Discrete/Ratio) | `int64` | Number of companies the employee worked for previously. |
| 22 | **Over18** | Qualitative (Nominal/Binary) | `object` | **Constant Feature**: Age verification (`Y`). Dropped during modeling. |
| 23 | **OverTime** | Qualitative (Nominal/Binary) | `object` | Whether the employee works overtime (`Yes`, `No`). |
| 24 | **PercentSalaryHike** | Quantitative (Discrete/Ratio) | `int64` | Percentage increase in salary last year. |
| 25 | **PerformanceRating** | Qualitative (Ordinal) | `int64` | Performance review rating (3: Excellent, 4: Outstanding). |
| 26 | **RelationshipSatisfaction** | Qualitative (Ordinal) | `int64` | Peer/management relationship satisfaction (1: Low, 2: Medium, 3: High, 4: Very High). |
| 27 | **StandardHours** | Quantitative (Discrete) | `int64` | **Constant Feature**: Standard working hours (always `80`). Dropped during modeling. |
| 28 | **StockOptionLevel** | Qualitative (Ordinal) | `int64` | Company stock option tier allocation (0 to 3). |
| 29 | **TotalWorkingYears** | Quantitative (Discrete/Ratio) | `int64` | Total professional experience career-wide. |
| 30 | **TrainingTimesLastYear** | Quantitative (Discrete/Ratio) | `int64` | Number of training sessions completed last year. |
| 31 | **WorkLifeBalance** | Qualitative (Ordinal) | `int64` | Work-life balance rating (1: Bad, 2: Good, 3: Better, 4: Best). |
| 32 | **YearsAtCompany** | Quantitative (Discrete/Ratio) | `int64` | Total tenure length at the current organization. |
| 33 | **YearsInCurrentRole** | Quantitative (Discrete/Ratio) | `int64` | Tenure duration specifically in the current job role. |
| 34 | **YearsSinceLastPromotion** | Quantitative (Discrete/Ratio) | `int64` | Years elapsed since the last formal job promotion. |
| 35 | **YearsWithCurrManager** | Quantitative (Discrete/Ratio) | `int64` | Number of years reporting to the current manager. |

* 2. Design a modular Python script to automate the initial data ingestion and
feature-label splitting process.

In [151]:
from sklearn.model_selection import train_test_split
def ingest_and_split_data(filepath, target_column, test_size=0.2, random_state=42):

    df = pd.read_csv(filepath)

    X = df.drop(columns=[target_column])
    y = df[target_column]

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=test_size, random_state=random_state, stratify=y)

    print(f"Total records: {len(df)}")
    print(f"Training features shape: {X_train.shape}")
    print(f"Testing features shape: {X_test.shape}")
    print(f"Shape: {df.shape}")
    print("\nDataset Information:")
    df.info()
    print(f"\nMissing Values:\n {df.isnull().sum()}")
    print(f"Feature Matrix Shape: {X.shape}")
    print(f"Label Vector Shape: {y.shape}")
    print("\nTarget Distribution:")
    print(df['Attrition'].value_counts())
    
    return X_train, X_test, y_train, y_test
X_train, X_test, y_train, y_test = ingest_and_split_data("WA_Fn-UseC_-HR-Employee-Attrition.csv", 'Attrition')

Total records: 1470
Training features shape: (1176, 34)
Testing features shape: (294, 34)
Shape: (1470, 35)

Dataset Information:
<class 'pandas.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   str
 2   BusinessTravel            1470 non-null   str
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   str
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   str
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   str
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   str
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   str
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   str
 22  OverTime                  1470 non-null   str
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(26), str(9)
memory usage: 510.8 KB

Missing Values:
 Age                         0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64
Feature Matrix Shape: (1470, 34)
Label Vector Shape: (1470,)

Target Distribution:
Attrition
No     1233
Yes     237
Name: count, dtype: int64

* 3. Map a Git-based model versioning strategy to track iterations of the HR attrition problem framing.

> main branch: Holds the stable, production-ready code.

> data-prep branch: Used specifically for cleaning data and engineering features.

> experiment/baseline-model branch:Used to establish the first baseline model (e.g., Logistic Regression).

> experiment/rf-tuning branch: Used for testing more complex models and tuning hyperparameters.

> Note on Data: Use DVC (Data Version Control) alongside Git to track changes to the actual CSV files without bloating the Git repository.

* 4. Construct a high-level architecture diagram illustrating the end-to-end ML lifecycle from raw CSV to model serving.

                    ┌──────────────────┐
                    │  HR CSV Dataset  │
                    │ (Raw Data File)  │
                    └────────┬─────────┘
                             │
                             ▼
                ┌────────────────────────┐
                │ Data Ingestion Module  │
                └────────┬───────────────┘
                         │
                         ▼
                ┌────────────────────────┐
                │ Data Validation & EDA  │
                └────────┬───────────────┘
                         │
                         ▼
                ┌────────────────────────┐
                │ Data Preprocessing     │
                │ • Missing Values       │
                │ • Encoding             │
                │ • Scaling              │
                └────────┬───────────────┘
                         │
                         ▼
                ┌────────────────────────┐
                │ Feature Engineering    │
                └────────┬───────────────┘
                         │
                         ▼
                ┌────────────────────────┐
                │ Train/Test Split       │
                └────────┬───────────────┘
                         │
                         ▼
                ┌────────────────────────┐
                │ Model Training         │
                │ Logistic Regression    │
                │ Random Forest          │
                │ XGBoost                │
                └────────┬───────────────┘
                         │
                         ▼
                ┌────────────────────────┐
                │ Model Evaluation       │
                │ Accuracy               │
                │ Precision              │
                │ Recall                 │
                │ F1 Score               │
                └────────┬───────────────┘
                         │
                         ▼
                ┌────────────────────────┐
                │ Model Versioning (Git) │
                └────────┬───────────────┘
                         │
                         ▼
                ┌────────────────────────┐
                │ Model Deployment       │
                │ REST API / Flask App   │
                └────────┬───────────────┘
                         │
                         ▼
                ┌────────────────────────┐
                │ Prediction Service     │
                │ Attrition Prediction   │
                └────────────────────────┘

### Section C:

### 1. Mini Project: Predictive Exit Interview System

* 2. Problem Statement: Develop an automated framework to identify high-risk
attrition candidates before they resign to improve retention rates.

In [152]:
df = pd.read_csv("WA_Fn-UseC_-HR-Employee-Attrition.csv")

In [153]:
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [154]:
df = df.drop(columns=['EmployeeCount', 'EmployeeNumber', 'StandardHours', 'Over18'])

In [155]:
from sklearn.preprocessing import LabelEncoder
df['Attrition'] = LabelEncoder().fit_transform(df['Attrition']) # Yes=1, No=0

In [156]:
df = pd.get_dummies(df, drop_first=True)
df.head()

,Age,Attrition,DailyRate,DistanceFromHome,Education,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,...,JobRole_Laboratory Technician,JobRole_Manager,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Married,MaritalStatus_Single,OverTime_Yes
0,41,1,1102,1,2,2,94,3,2,4,...,False,False,False,False,False,True,False,False,True,True
1,49,0,279,8,1,3,61,2,2,2,...,False,False,False,False,True,False,False,True,False,False
2,37,1,1373,2,2,4,92,2,1,3,...,True,False,False,False,False,False,False,False,True,True
3,33,0,1392,3,4,4,56,3,1,3,...,False,False,False,False,True,False,False,True,False,True
4,27,0,591,2,1,1,40,3,1,2,...,True,False,False,False,False,False,False,True,False,False

In [157]:
X = df.drop('Attrition', axis=1)
y = df['Attrition']

In [158]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=42)

In [159]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=100, random_state=42, class_weight='balanced')

rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)

In [160]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("\nAccuracy:")
print(accuracy_score(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy:
0.8741496598639455

Classification Report:
              precision    recall  f1-score   support

           0       0.88      1.00      0.93       255
           1       0.75      0.08      0.14        39

    accuracy                           0.87       294
   macro avg       0.81      0.54      0.54       294
weighted avg       0.86      0.87      0.83       294


Confusion Matrix:
[[254   1]
 [ 36   3]]

In [161]:
importance = pd.DataFrame({
    'Feature': X.columns,
    'Importance': rf.feature_importances_})

importance = importance.sort_values(by='Importance', ascending=False)

print("\nTop Features:")
importance.head(15).style.background_gradient(cmap='Reds')

Top Features:

* 4. Required Deliverables: ML Project Charter (PDF), Feature Importance Table,
Proposed Workflow Pipeline Diagram

# Predictive Exit Interview System Flowchart


```text
+--------------------------------------------------+
|          PREDICTIVE EXIT INTERVIEW SYSTEM        |
+--------------------------------------------------+
                       |
                       v
+--------------------------------------------------+
|                IBM HR ATTRITION DATASET          |
+--------------------------------------------------+
                       |
                       v
+--------------------------------------------------+
|                DATA PREPROCESSING                |
|--------------------------------------------------|
| • Handle Missing Values                          |
| • Remove Duplicates                              |
| • Encode Categorical Features                    |
| • Feature Scaling (if required)                  |
+--------------------------------------------------+
                       |
                       v
+--------------------------------------------------+
|               FEATURE ENGINEERING                |
|--------------------------------------------------|
| • Select Important Features                      |
| • Remove Irrelevant Columns                      |
+--------------------------------------------------+
                       |
                       v
+--------------------------------------------------+
|                 TRAIN-TEST SPLIT                 |
|--------------------------------------------------|
| • Training Data (80%)                            |
| • Testing Data (20%)                             |
+--------------------------------------------------+
                       |
                       v
+--------------------------------------------------+
|              MACHINE LEARNING MODEL              |
|--------------------------------------------------|
| • Random Forest Classifier                       |
+--------------------------------------------------+
                       |
                       v
+--------------------------------------------------+
|                 MODEL EVALUATION                 |
|--------------------------------------------------|
| • Accuracy                                       |
| • Precision                                      |
| • Recall                                         |
| • F1-Score                                       |
| • Confusion Matrix                               |
+--------------------------------------------------+
                       |
                       v
+--------------------------------------------------+
|                FEATURE IMPORTANCE                |
|--------------------------------------------------|
| • Monthly Income                                 |
| • Overtime                                       |
| • Age                                            |
| • Job Satisfaction                               |
| • Years At Company                               |
+--------------------------------------------------+
                       |
                       v
+--------------------------------------------------+
|               ATTRITION PREDICTION               |
|--------------------------------------------------|
| • High Risk Employee                             |
| • Medium Risk Employee                           |
| • Low Risk Employee                              |
+--------------------------------------------------+
                       |
                       v
+--------------------------------------------------+
|                HR DECISION SUPPORT               |
|--------------------------------------------------|
| • Retention Strategies                           |
| • Employee Engagement Programs                   |
| • Exit Prevention Actions                        |
+--------------------------------------------------+
```